- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Disable Default Redis
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable Redis 7 Version
  ansible.builtin.shell: dnf module enable redis:7 -y

- name: Install redis 
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update Redis Listen address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

# chrome:- replace line ansible module (4:56) ansible.builtin.lineinfile module- manage lines in text files

- name: Update Redis Dissable protection
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: protected-mode no

- name: Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restrated
    enabled: yes



