- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
    dest: /app
    remote_src: yes

